---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: odf-lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: vg1
      deviceSelector: 
        paths:
          - /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
          - /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
          - /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90
        overprovisionRatio: 10