---
apiVersion: v1
kind: Secret
metadata:
  name: controller-auth-account
  namespace: image-builder
type: Opaque
stringData:
  controller_hostname: '{{ controller_hostname }}'
  controller_username: 'admin'
  controller_password: '{{ controller_password }}'
  controller_validate_certs: 'false'